### ISSUE TITLE
[Request] Create a platform underneath the player

### ISSUE THREAD

**Issue by lnxredir** [voltration/easyRTP#2]
Hello! Do you think you can add a toggle to add a platform underneath the player when he teleports? Say I create a void world, when the player runs /rtp, he gets teleported and underneath him a 2x2 obsidian platform appears. I would love for a feature like this to be added. Cheers!

**Comment by voltration** [comment]
> Hello! Do you think you can add a toggle to add a platform underneath the player when he teleports? Say I create a void world, when the player runs /rtp, he gets teleported and underneath him a 2x2 obsidian platform appears. I would love for a feature like this to be added. Cheers!

Sure, give me a day or two to write it
